name: ci
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup
      run: |
        sudo apt update
        sudo apt install -y gcc libgtk-3-dev libappindicator3-dev golang ca-certificates

    - name: run
      run: make build

