name: release-ubuntu-latest
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup
      run: |
        apt update
        apt install -y make gcc libgtk-3-dev libappindicator3-dev golang ca-certificates

    - name: run
      run: make build

    - name: upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bluebao
        asset_name: bluebao-ubuntu-latest
        tag: latest
        overwrite: true

