name: release
on:
  push:
    branches: [ main ]
  schedule:
    # Daily at 13:59
    - cron: '13 59 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:rolling
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup
      run: |
        sudo apt update
        sudo apt install -y gcc libgtk-3-dev libappindicator3-dev golang ca-certificates

    - name: run
      run: make build

    - name: upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bluebao
        asset_name: bluebao-ubuntu-latest
        tag: latest
        overwrite: true

